### ISSUE TITLE
nil cells cause NPE

### ISSUE THREAD

**Issue by jasonab** [davidsantiago/clojure-csv#22]
Given a sequence that contains nil entries, needs-quote? throws NullPointerException:

java.lang.NullPointerException: null
                     core.clj:228 clojure-csv.core/needs-quote?
                     core.clj:244 clojure-csv.core/quote-and-escape
                     core.clj:255 clojure-csv.core/quote-and-escape-row[fn]

**Comment by sxb8au** [comment]
Agree with the sentiment, but in practice, every user if the library will end up writing a nil conversion function. fwiw, I tend to think it would be a good idea for this feature to be implemented, if only for the pragmatic reason of saving a little effort on behalf of 1000's of happy nil passing users.
