### ISSUE TITLE
Commas inside quotes

### ISSUE THREAD

**Issue by unhandyandy** [davidsantiago/clojure-csv#36]
Does this parser ignore commas inside quotes when splitting fields, as I hope it does?

Since you said "Quoting and escaping inside CSV fields are handled correctly (specifically commas and double-quote characters)," I'm assuming the answer is Yes.

**Comment by davidsantiago** [comment]
Yes, it does handle them correctly. Separators in quoted fields are not treated as separators. Quotes can be escaped inside quoted fields.

**Comment by unhandyandy** [comment]
Thank you!
